### PR TITLE
Update to EDGARv5.0_FT2017 dataset

### PR DESCRIPTION
**Pull request by dancunningham**
- Updated the dataset to EDGARv5.0_FT2017, published 2018-11-23 (to which I added back the country codes)
- Updated script based on changes in format of published data
- Updated output data
- Updated JSON and README files

I checked that the sum of the output data matched the sum of the input data.

There were a couple of noteworthy changes to the data in v5.0:
- "Non-combustion" sector was renamed to "Other sectors"
- EU28 and WORLD groupings were no longer present in the data

### CODE REVIEW

**Comment by rgieseke** [comment]
Awesome, many thanks! Had not noticed the update yet ...

**Comment by rgieseke** [comment]
@dancunningham  How did you create the CSV, is this from the XLS file on the website?

**Comment by dancunningham** [comment]
Yes, from the link at https://edgar.jrc.ec.europa.eu/overview.php?v=booklet2018 to https://edgar.jrc.ec.europa.eu/booklet2018/EDGARv5.0_FT2017_fossil_CO2_booklet2018.xls

I took the data in the "fossil_CO2_by_sector_and_countr" sheet and added back in the country codes.

**Comment by rgieseke** [comment]
Sorry for the very long delay! I've done this by reading directly from the original Excel file and cherry-picked your very welcome edits to the Readme and Metadata :-)

**Pull request closed without merging**
